export const generateToolContent = (repoNames: string[]): string => {
	const techList = repoNames.join(', ');
	const techUnion = repoNames.join(' | ');

	return `import { tool } from "@opencode-ai/plugin"

// Generated by btca sync. Re-run 'btca sync' after adding/removing repos.

export default tool({
  description: "Ask questions about framework/library source code using btca. Available: ${techList}",
  args: {
    tech: tool.schema.string().describe("Technology: ${techUnion}"),
    question: tool.schema.string().describe("Question about the framework/library"),
  },
  async execute(args) {
    const result = await Bun.$\`btca ask -t \${args.tech} -q \${args.question}\`.text()
    return result.trim()
  },
})
`;
};

export const generateAgentContent = (repoNames: string[]): string => {
	const techList = repoNames.join(', ');

	return `---
description: Answer questions about frameworks by analyzing their source code
mode: subagent
tools:
  btca: true
  write: false
  edit: false
  bash: false
---

You have access to btca for querying framework documentation and source code.

Available technologies: ${techList}

Use the btca tool to answer questions. It analyzes actual source code repositories.
`;
};
