export interface RepoInfo {
	name: string;
	url: string;
	specialNotes?: string;
}

export const generateToolContent = (repos: RepoInfo[]): string => {
	const techList = repos.map((r) => r.name).join(', ');
	const techUnion = repos.map((r) => r.name).join(' | ');

	return `import { tool } from "@opencode-ai/plugin"

// Generated by btca sync. Re-run 'btca sync' after adding/removing repos.

export default tool({
  description: "Query library source code and documentation using btca. This tool clones repos locally and uses AI to search and analyze the actual codebase. Available: ${techList}",
  args: {
    tech: tool.schema.string().describe("Technology to query: ${techUnion}"),
    question: tool.schema.string().describe("Question about the library. Be specific - include version info, API names, or use cases when relevant."),
  },
  async execute(args) {
    const result = await Bun.$\`btca ask -t \${args.tech} -q \${args.question}\`.text()
    return result.trim()
  },
})
`;
};

export const generateAgentContent = (repos: RepoInfo[]): string => {
	const techList = repos.map((r) => r.name).join(', ');

	// Build per-tech context section
	const techContextLines = repos
		.map((r) => {
			if (r.specialNotes) {
				return `- **${r.name}**: ${r.specialNotes}`;
			}
			return `- **${r.name}**: Source from ${r.url}`;
		})
		.join('\n');

	return `---
description: Answer questions about libraries by analyzing their actual source code
mode: subagent
tools:
  btca: true
  write: false
  edit: false
  bash: false
---

You are a documentation expert with access to btca, a tool that queries library source code directly.

## How btca works

btca clones repositories locally and uses AI to search and analyze the actual codebase. This means answers are based on real source code, not potentially outdated documentation.

## Available technologies

${techContextLines}

## Usage tips

- Ask specific questions - include API names, version requirements, or specific use cases
- One question at a time works best
- The tool searches actual source code, so questions about implementation details work well
- If you need multiple pieces of information, make separate btca calls

## When to use btca

Use btca when the user asks about:
- How to use a specific API or feature in ${techList}
- Implementation patterns or best practices
- Code examples for specific use cases
- Understanding how something works under the hood
`;
};
